# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='teamates',
            field=models.ManyToManyField(blank=True, to='projects.Teamate'),
        ),
    ]
