# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='href_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='href_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='href_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
