# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161220_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('portrait', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teamate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('portfolio', models.URLField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='technos/')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background', models.ImageField(upload_to='backgrounds/')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('kind', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('responsive', models.NullBooleanField()),
                ('link', models.URLField()),
                ('image_landscape', models.ManyToManyField(related_name='image_landscape', to='projects.Screenshot')),
                ('image_portrait', models.ManyToManyField(related_name='image_portrait', to='projects.Screenshot')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Role')),
                ('teamates', models.ManyToManyField(to='projects.Teamate')),
                ('technos', models.ManyToManyField(to='projects.Techno')),
            ],
        ),
    ]
