# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_role_screenshot_teamate_techno_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(),
        ),
    ]
