# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170120_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='href',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='screenshot',
            old_name='href_en',
            new_name='alt_en',
        ),
        migrations.RenameField(
            model_name='screenshot',
            old_name='href_es',
            new_name='alt_es',
        ),
        migrations.RenameField(
            model_name='screenshot',
            old_name='href_fr',
            new_name='alt_fr',
        ),
        migrations.AddField(
            model_name='work',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='desc_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='desc_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
