# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170105_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
