# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170122_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='alt_en',
        ),
        migrations.RemoveField(
            model_name='work',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='work',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='work',
            name='title_en',
        ),
    ]
