# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170122_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='work',
            name='name_fr',
        ),
    ]
