# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170123_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='people',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
