# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170123_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='alt_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
