# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170123_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamate',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Role'),
        ),
    ]
